name: Build LogBeetle Windows Binary
run-name: ${{ gitea.actor }} is Build Windows Actions 🚀

on: [push]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: verify proxy
        run: |
          echo $http_proxy
          echo $https_proxy

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
        env:
          GOPROXY: https://goproxy.cn
          GO111MODULE: on

      - name: Install dependencies
        run: go mod tidy

      - name: Build LogBeetle (Windows)
        run: |
          echo `pwd`
          echo `ls -alh`
          bash package.sh

      - name: Install MinIO Client
        run: |
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv mc /usr/local/bin/mc

      - name: Configure MinIO Client
        run: |
          mc alias set minio ${{ secrets.MINIO_ENDPOINT }} ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}

      - name: Upload binary to MinIO
        run: |
          mc cp ./bin minio/releases/LogBeetle/