// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/log-beetle/v1/": {
            "get": {
                "description": "首页",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "管理"
                ],
                "summary": "首页",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.AboutResponse"
                        }
                    }
                }
            }
        },
        "/log-beetle/v1/about": {
            "get": {
                "description": "关于",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理"
                ],
                "summary": "关于",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/log-beetle/v1/log/add": {
            "post": {
                "description": "添加日志",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志管理"
                ],
                "summary": "添加日志",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddLogRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.JSONResult"
                        }
                    }
                }
            }
        },
        "/log-beetle/v1/log/addTestData": {
            "post": {
                "description": "添加测试日志",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志管理"
                ],
                "summary": "添加测试日志",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.JSONResult"
                        }
                    }
                }
            }
        },
        "/log-beetle/v1/log/search": {
            "post": {
                "description": "日志搜索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志管理"
                ],
                "summary": "搜索日志",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.JSONResult"
                        }
                    }
                }
            }
        },
        "/log-beetle/v1/nsq/register-topic": {
            "post": {
                "description": "发送消息到 NSQ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NSQ"
                ],
                "summary": "列出 NSQ 注册的 topic",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RequestGetNsqTopicList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.JSONResult"
                        }
                    }
                }
            }
        },
        "/log-beetle/v1/ping": {
            "get": {
                "description": "ping",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "管理"
                ],
                "summary": "ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/log-beetle/v1/send-message": {
            "post": {
                "description": "发送消息到nsq",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "消息管理"
                ],
                "summary": "发送消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "message",
                        "name": "message",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "project_name",
                        "name": "project_name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.JSONResult"
                        }
                    }
                }
            }
        },
        "/log-beetle/v1/store/delete": {
            "post": {
                "description": "删除指定日志仓",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志存储管理"
                ],
                "summary": "删除指定日志仓",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DeleteStoreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.JSONResult"
                        }
                    }
                }
            }
        },
        "/log-beetle/v1/store/list": {
            "post": {
                "description": "查询日志仓信息列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志存储管理"
                ],
                "summary": "查询日志仓信息列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.JSONResult"
                        }
                    }
                }
            }
        },
        "/log-beetle/v1/store/names": {
            "post": {
                "description": "查询日志仓名称列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志存储管理"
                ],
                "summary": "查询日志仓名称列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.JSONResult"
                        }
                    }
                }
            }
        },
        "/log-beetle/v1/system/system-info": {
            "post": {
                "description": "获取系统信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "获取系统信息",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SystemInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.JSONResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AboutResponse": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                }
            }
        },
        "model.AddLogRequest": {
            "type": "object",
            "properties": {
                "clientip": {
                    "description": "客户端IP",
                    "type": "string"
                },
                "date": {
                    "description": "日期（格式YYYY-MM-DD HH:MM:SS.SSS）",
                    "type": "string"
                },
                "id": {
                    "description": "从1开始递增",
                    "type": "string"
                },
                "loglevel": {
                    "description": "日志级别（debug、info、warn、error）",
                    "type": "string"
                },
                "serverip": {
                    "description": "服务器IP",
                    "type": "string"
                },
                "servername": {
                    "description": "服务器名",
                    "type": "string"
                },
                "system": {
                    "description": "系统名",
                    "type": "string"
                },
                "text": {
                    "description": "【必须】日志内容，多行时仅为首行，直接显示用，是全文检索对象",
                    "type": "string"
                },
                "traceid": {
                    "description": "跟踪ID",
                    "type": "string"
                },
                "user": {
                    "description": "用户",
                    "type": "string"
                }
            }
        },
        "model.DeleteStoreRequest": {
            "type": "object",
            "properties": {
                "store_name": {
                    "type": "string"
                }
            }
        },
        "model.JSONResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "model.RequestGetNsqTopicList": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "sort_by": {
                    "type": "string"
                }
            }
        },
        "model.SearchRequest": {
            "type": "object",
            "properties": {
                "current_id": {
                    "description": "当前ID",
                    "type": "string"
                },
                "current_store_name": {
                    "description": "当前门店名称",
                    "type": "string"
                },
                "datetime_from": {
                    "description": "开始时间",
                    "type": "string"
                },
                "datetime_to": {
                    "description": "结束时间",
                    "type": "string"
                },
                "forward": {
                    "description": "前向（可能是方向或者其他标识）",
                    "type": "string"
                },
                "log_level": {
                    "description": "日志级别",
                    "type": "string"
                },
                "near_store_name": {
                    "description": "邻近门店名称",
                    "type": "string"
                },
                "new_near_id": {
                    "description": "新邻近ID",
                    "type": "string"
                },
                "old_near_id": {
                    "description": "旧邻近ID",
                    "type": "string"
                },
                "search_key": {
                    "description": "消费者信息",
                    "type": "string"
                },
                "store_name": {
                    "description": "门店名称编号或ID",
                    "type": "string"
                },
                "system": {
                    "description": "系统信息",
                    "type": "string"
                },
                "user": {
                    "description": "用户信息",
                    "type": "string"
                }
            }
        },
        "model.SystemInfoRequest": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
