definitions:
  logdata.LogDataModel:
    properties:
      clientip:
        description: 客户端IP
        type: string
      date:
        description: 日期（格式YYYY-MM-DD HH:MM:SS.SSS）
        type: string
      detail:
        description: 【内部字段】多行时的详细日志信息，通常是包含错误堆栈等的日志内容
        type: string
      id:
        description: 从1开始递增
        type: string
      loglevel:
        description: 日志级别（debug、info、warn、error）
        type: string
      serverip:
        description: 服务器IP
        type: string
      servername:
        description: 服务器名
        type: string
      storename:
        description: 日志仓名称（未存储，仅赋值给前端使用）
        type: string
      system:
        description: 系统名
        type: string
      text:
        description: 【必须】日志内容，多行时仅为首行，直接显示用，是全文检索对象
        type: string
      traceid:
        description: 跟踪ID
        type: string
      user:
        description: 用户
        type: string
    type: object
  model.AboutResponse:
    properties:
      title:
        type: string
    type: object
  model.JSONResult:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  model.RequestGetNsqTopicList:
    properties:
      desc:
        type: boolean
      page:
        type: integer
      page_size:
        type: integer
      sort_by:
        type: string
    type: object
  model.SearchRequest:
    properties:
      current_id:
        description: 当前ID
        type: string
      current_store_name:
        description: 当前门店名称
        type: string
      datetime_from:
        description: 开始时间
        type: string
      datetime_to:
        description: 结束时间
        type: string
      forward:
        description: 前向（可能是方向或者其他标识）
        type: string
      log_level:
        description: 日志级别
        type: string
      near_store_name:
        description: 邻近门店名称
        type: string
      new_near_id:
        description: 新邻近ID
        type: string
      old_near_id:
        description: 旧邻近ID
        type: string
      search_key:
        description: 消费者信息
        type: string
      store_name:
        description: 门店名称编号或ID
        type: string
      system:
        description: 系统信息
        type: string
      user:
        description: 用户信息
        type: string
    type: object
  model.SystemInfoRequest:
    type: object
info:
  contact: {}
paths:
  /log-beetle/v1/:
    get:
      consumes:
      - text/plain
      description: 首页
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AboutResponse'
      summary: 首页
      tags:
      - 管理
  /log-beetle/v1/about:
    get:
      consumes:
      - text/plain
      description: 关于
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 关于
      tags:
      - 管理
  /log-beetle/v1/log/add:
    post:
      consumes:
      - application/json
      description: 添加日志
      parameters:
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/logdata.LogDataModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.JSONResult'
      summary: 添加日志
      tags:
      - 日志管理
  /log-beetle/v1/log/addTestData:
    post:
      consumes:
      - application/json
      description: 添加测试日志
      parameters:
      - description: 请求参数
        in: body
        name: request
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.JSONResult'
      summary: 添加测试日志
      tags:
      - 日志管理
  /log-beetle/v1/log/search:
    post:
      consumes:
      - application/json
      description: 日志搜索
      parameters:
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SearchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.JSONResult'
      summary: 搜索日志
      tags:
      - 日志管理
  /log-beetle/v1/nsq/register-topic:
    post:
      consumes:
      - application/json
      description: 发送消息到 NSQ
      parameters:
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RequestGetNsqTopicList'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.JSONResult'
      summary: 列出 NSQ 注册的 topic
      tags:
      - NSQ
  /log-beetle/v1/ping:
    get:
      consumes:
      - text/plain
      description: ping
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping
      tags:
      - 管理
  /log-beetle/v1/send-message:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 发送消息到nsq
      parameters:
      - description: message
        in: formData
        name: message
        required: true
        type: string
      - description: project_name
        in: formData
        name: project_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.JSONResult'
      summary: 发送消息
      tags:
      - 消息管理
  /log-beetle/v1/store/delete:
    post:
      consumes:
      - application/json
      description: 删除指定日志仓
      parameters:
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SearchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.JSONResult'
      summary: 删除指定日志仓
      tags:
      - 日志存储管理
  /log-beetle/v1/store/list:
    post:
      consumes:
      - application/json
      description: 查询日志仓信息列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.JSONResult'
      summary: 查询日志仓信息列表
      tags:
      - 日志存储管理
  /log-beetle/v1/store/names:
    post:
      consumes:
      - application/json
      description: 查询日志仓名称列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.JSONResult'
      summary: 查询日志仓名称列表
      tags:
      - 日志存储管理
  /log-beetle/v1/system/system-info:
    post:
      consumes:
      - application/json
      description: 获取系统信息
      parameters:
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SystemInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.JSONResult'
      summary: 获取系统信息
      tags:
      - 系统
swagger: "2.0"
